# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# '/Users/admin/Documents/GitHub/CleanFolder_App/CleanFolder_App/qt_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from main import file_parser
from time import time
from tqdm import tqdm
from pathlib import Path

folder = ''
start_flag = True


def welcome():
    if start_flag:
        ui.textBrowser.setText(f'Welcome to CleanFolder'
                               '\n'
                               'This app is for organizing files in your folders'
                               '\n'
                               'For Start app - click button ...')



def get_path():
    global folder
    folder = ui.folderpath.getExistingDirectory()
    return folder


logs = ''


# def bar():
#     pbar = tqdm(sorted(Path(folder).glob("**/*")))
#     for char in pbar:
#         ui.textBrowser.setText(pbar.set_description("Processing %s" % char))


def click():
    global start_flag
    start_flag = False
    if folder != '':
        # bar()
        timer = time()
        file_parser(folder)
        ui.textBrowser.setText(f'Files in {folder} sorted succesffully'
                               '\n'
                               f'During {round(time() - timer, 4)} sec')
    elif folder == '':
        ui.textBrowser.setText('Choose your folder, click button ...')


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(443, 364)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(200, 10, 231, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.toolButton.clicked.connect(get_path)

        self.folderpath = QtWidgets.QFileDialog(MainWindow, 'Select Folder')

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 60, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(click)

        # self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        # self.progressBar.setGeometry(QtCore.QRect(20, 120, 401, 30))
        # self.progressBar.setProperty("value", 0)
        # self.progressBar.setObjectName("progressBar")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 150, 371, 161))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textBrowser.setFont(font)

        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)


        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CleanFolder"))
        self.label.setText(_translate("MainWindow", "Choose your folder "))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "Start"))




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    welcome()


    sys.exit(app.exec_())
